### ISSUE TITLE
add optional memo

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-pay#144]
when sending some sats as an anonymous donation, someone may want to add a comment on it.

currently this is possible to have a Memo from the mobile when sending to another user. there is no way to do it currently from galoy-pay.

it may require some update on the backend. Also important to take into consideration the anti spam measure on the memo.

**Comment by bodymindarts** [comment]
AFACT backend support exists. It might be interesting to report back to the user that the memo will not be delivered if the amount is below the spam threshold.

**Comment by nicolasburtey** [comment]
> AFACT backend support exists.

yes it does indeed. mobile is using it

**Comment by jamespierog** [comment]
Where could you query to find the spam threshold? I haven't been able to find it on the API reference.

**Comment by vindard** [comment]
> Where could you query to find the spam threshold? I haven't been able to find it on the API reference.

It gets applied [here](https://github.com/GaloyMoney/galoy/blob/e04b3d11fd565b506b0bdb6fdf22c0b6ae91154f/src/domain/wallets/tx-history.ts#L219) internally. I don't think we expose explicitly in any gql queries

**Comment by bodymindarts** [comment]
@jamespierog if you need it for this work we can statically configure / inject the same value we inject in the backend

**Comment by jamespierog** [comment]
If the regular wallet error handling already takes care of it then it should be okay since the error would be returned in the transaction. If that UX is sufficient then I can move forward with building that (just adding a memo form input and connecting it to the gql mutations without adding extra error handling in case the amount is below the spam threshold). 

But if we want to let the user know beforehand that their transaction amount is below the spam threshold, then we would need that amount queryable in advance. I think that would be a better UX (people don't need to send transactions twice in the event of a failure) so it might be a good idea to inject that value in the backend.

**Comment by bodymindarts** [comment]
> If the regular wallet error handling already takes care of it then it should be okay since the error would be returned in the transaction. If that UX is sufficient then I can move forward with building that (just adding a memo form input and connecting it to the gql mutations without adding extra error handling in case the amount is below the spam threshold).
> 
> But if we want to let the user know beforehand that their transaction amount is below the spam threshold, then we would need that amount queryable in advance. I think that would be a better UX (people don't need to send transactions twice in the event of a failure) so it might be a good idea to inject that value in the backend.

For UX it would be good but just FYI the tx will not fail it will just not be shown to the receiving party. The memo will be accepted by the backend but not forwarded - this is an anti spam measure. I think its fine not to expose it for now.

**Comment by jamespierog** [comment]
All right sounds good. I'll just go ahead with that first implementation idea without the need of any query.

**Comment by Extheoisah** [comment]
closed by https://github.com/GaloyMoney/galoy-pay/pull/352
